grammar LITE;
PROGRAMA: CUERPO;
CUERPO: PR_INICIO (SENTENCIA)* PR_FIN;
SENTENCIA: DECLARACION | ASIGNACION | SENTENCIA_SI | SENTENCIA_MIENTRAS | SENTENCIA_IMPRIMIR | OTRO;
DECLARACION : PR_CREA VARIABLE PR_DECLARADOR TIPO PR_FIN_SENTENCIA;
ASIGNACION: VARIABLE PR_ASIGNADOR EXPRESION PR_FIN_SENTENCIA;
SENTENCIA_SI: PR_SI PR_PARENTESIS_A EXPRESION_LOGICA PR_PARENTESIS_C PR_ENTONCES (SENTENCIA)* (SENTENCIA_SINO)? PR_FIN;
SENTENCIA_MIENTRAS: 

